spring:
  application:
    name: tutorial-eureka
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    org.springframework.boot.context.config: DEBUG